server:
  port: 9090

spring:
  application:
    name: ClientContactsManager

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: 12345
    locations: classpath:db/migration
